config/routes.rb
SchoolPlanner::Application.routes.draw do
  root 'calendars#week'

  resources :projects

  resources :tests

  resources :homeworks

  resources :courses

  resources :practices

  resources :groups

  resources :days

  

end

app/models/day.rb
class Day < ActiveRecord::Base
	has_many :practices
	has_many :projects
	has_many :tests 
	has_many :homeworks

	validates :day, presence: true	
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:day)
    end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong><%= pluralize(@day.errors.count, "error") %> prohibited this test from being saved:</strong> 
      <ul>
        <% @day.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.date_select :day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<h1>listing days</h1>

<table class="table content-table">
  <thead>
    <tr>
      <th>Day</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= day.day %></td>
        <td><%= link_to 'Show', day, :class => 'btn btn-default btn-small' %></td>
        <td><%= link_to 'Edit', edit_day_path(day), :class => 'btn btn-warning btn-small' %></td>
        <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-small' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Day', new_day_path, :class => 'btn btn-primary btn-large' %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>


<div class="page-header">
  <h1><%= @day.day %> <small>date</small></h1>
</div>

<p class="lead">Tests:</p>
<% @day.tests.each do |test| %>
	<div class="list-group">
	  <div class="list-group-item">
	    <h4 class="list-group-item-heading"><%= test.subject %></h4>
	    <p class="list-group-item-text"><%= test.course.name %></p>
	  </div>
	</div>
<% end %>
<p><%= link_to 'add test', new_test_path(@day.tests) %></p>

<p class="lead">Homework:</p>
<% @day.homeworks.each do |homework| %>
	<div class="list-group">
	  <div class="list-group-item">
	    <h4 class="list-group-item-heading"><%= homework.assignment %></h4>
	    <p class="list-group-item-text"><%= homework.course.name %></p>
	  </div>
	</div>
<% end %>
<p><%= link_to 'add homework', new_homework_path(@day.homeworks) %></p>

<p class="lead">Projects:</p>
<% @day.projects.each do |project| %>
	<div class="list-group">
	  <div class="list-group-item">
	    <h4 class="list-group-item-heading"><%= project.name %></h4>
	    <p class="list-group-item-text"><%= project.requirements %></p>
	    <p class="list-group-item-text"><%= project.course.name %></p>
	  </div>
	</div>
<% end %>
<p><%= link_to 'add project', new_project_path(@day.projects) %></p>

<p class="lead">Practices:</p>
<% @day.practices.each do |practice| %>
	<div class="list-group">
	  <div class="list-group-item">
	    <h4 class="list-group-item-heading"><%= practice.group.name %></h4>
	  </div>
	</div>
<% end %>
<p><%= link_to 'add practice', new_practice_path(@day.practices) %></p>

<hr></hr> 

<%= link_to 'edit', edit_day_path(@day) %> |
<%= link_to 'back', days_path %>