config/routes.rb
SchoolPlanner::Application.routes.draw do
  root 'calendars#week'

  resources :projects

  resources :tests

  resources :homeworks

  resources :courses

  resources :practices

  resources :groups

  resources :days

  

end

app/models/practice.rb
class Practice < ActiveRecord::Base
	belongs_to :day
	belongs_to :group

	validates :group_id, :day_id, presence: true
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice, only: [:show, :edit, :update, :destroy]

  # GET /practices
  # GET /practices.json
  def index
    @practices = Practice.all
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit
  end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(practice_params)

    respond_to do |format|
      if @practice.save
        format.html { redirect_to @practice, notice: 'Practice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @practice }
      else
        format.html { render action: 'new' }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1
  # PATCH/PUT /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to @practice, notice: 'Practice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice.destroy
    respond_to do |format|
      format.html { redirect_to practices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_params
      params.require(:practice).permit(:group_id, :day_id)
    end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/_form.html.erb
<%= form_for(@practice) do |f| %>
  <% if @practice.errors.any? %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong><%= pluralize(@practice.errors.count, "error") %> prohibited this test from being saved:</strong> 
      <ul>
        <% @practice.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.select( :group_id, options_from_collection_for_select(Group.all, :id, :name)) %>
  </div>
  <div class="field">
    <%= f.label :day_id %><br>
    <%= f.select( :day_id, options_from_collection_for_select(Day.all, :id, :day)) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/practices/edit.html.erb
<h1>Editing practice</h1>

<%= render 'form' %>

<%= link_to 'Show', @practice %> |
<%= link_to 'Back', practices_path %>

app/views/practices/index.html.erb
<h1>listing practices</h1>

<table class="table content-table">
  <thead>
    <tr>
      <th>Group</th>
      <th>Day</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= practice.group.name %></td>
        <td><%= practice.day.day %></td>
        <td><%= link_to 'Show', practice, :class => 'btn btn-default btn-small' %></td>
        <td><%= link_to 'Edit', edit_practice_path(practice), :class => 'btn btn-warning btn-small' %></td>
        <td><%= link_to 'Destroy', practice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-small' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Practice', new_practice_path, :class => 'btn btn-primary btn-large' %>

app/views/practices/new.html.erb
<h1>New practice</h1>

<%= render 'form' %>

<%= link_to 'Back', practices_path %>

app/views/practices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <p class="lead">Group:</p>
  	<div class="list-group">
	 <div class="list-group-item">
	   <h4 class="list-group-item-heading"><%= @practice.group.name %></h4>
	 </div>
	</div>
</p>



<p>
  <p class="lead">Day:</p>
	<div class="list-group">
	 <div class="list-group-item">
	   <h4 class="list-group-item-heading"><%= @practice.day.day %></h4>
	 </div>
	</div>  
</p>



<hr></hr>

<%= link_to 'edit', edit_practice_path(@practice) %> |
<%= link_to 'back', practices_path %>