config/routes.rb
SchoolPlanner::Application.routes.draw do
  root 'calendars#week'

  resources :projects

  resources :tests

  resources :homeworks

  resources :courses

  resources :practices

  resources :groups

  resources :days

  

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong><%= pluralize(@course.errors.count, "error") %> prohibited this test from being saved:</strong> 
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>listing courses</h1>

<table class="table content-table">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course, :class => 'btn btn-default btn-small' %></td>
        <td><%= link_to 'Edit', edit_course_path(course), :class => 'btn btn-warning btn-small' %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-small' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path, :class => 'btn btn-primary btn-large' %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><%= @course.name %> <small>course name</small></h1>
</div>

<p class="lead">Assignments:</p>
<% @course.homeworks.each do |homework| %>
	<div class="list-group">
	  <div class="list-group-item">
	    <h4 class="list-group-item-heading"><%= homework.assignment %></h4>
		<p class="list-group-item-text"><%= homework.day.day %></p>
	  </div>
	</div>
<% end %>
<p><%= link_to 'add assignment', new_homework_path %></p>

<p class="lead">Tests:</p>
<% @course.tests.each do |test| %>
	<div class="list-group">
	  <div class="list-group-item">
	    <h4 class="list-group-item-heading"><%= test.subject %></h4>
		<p class="list-group-item-text"><%= test.day.day %></p>
	  </div>
	</div>
<% end %>
<p><%= link_to 'add test', new_test_path %></p>

<p class="lead">Projects:</p>
<% @course.projects.each do |project| %>
	<div class="list-group">
	  <div class="list-group-item">
	    <h4 class="list-group-item-heading"><%= project.name %></h4>
		<p class="list-group-item-text"><%= project.requirements %></p>
		<p class="list-group-item-text"><%= project.day.day %></p>
	  </div>
	</div>
<% end %>
<p><%= link_to 'add project', new_project_path %></p>

<hr></hr>

<%= link_to 'edit', edit_course_path(@course) %> |
<%= link_to 'back', courses_path %>